version: '3.9'

services:
  price-service:
    platform: linux/amd64
    build:
      context: ./PriceService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5001:8080"        
    networks: [backend]
    
  log-service:
    platform: linux/amd64
    build:
      context: ./LogService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5003:8080"
    networks: [ backend ]

  product-service:
    platform: linux/amd64
    build:
      context: .                      
      dockerfile: ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    depends_on: [price-service]
    ports:
      - "5002:8080"
    networks: [backend]

networks:
  backend: