# This is a generated file. Not intended for manual editing.
services:
  log-service:
    build:
      context: "/Users/test/Desktop/pet_microservice/LogService"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/LogService.dll"
    environment: {}
    image: "logservice:dev"
    ports: []
    volumes:
    - "/Users/test/Desktop/pet_microservice/LogService:/app:rw"
    - "/Users/test/Desktop/pet_microservice:/src:rw"
    - "/Users/test/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
  price-service:
    build:
      context: "/Users/test/Desktop/pet_microservice/PriceService"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/PriceService.dll"
    environment: {}
    image: "priceservice:dev"
    ports: []
    volumes:
    - "/Users/test/Desktop/pet_microservice/PriceService:/app:rw"
    - "/Users/test/Desktop/pet_microservice:/src:rw"
    - "/Users/test/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
  product-service:
    build:
      context: "/Users/test/Desktop/pet_microservice"
      dockerfile: "ProductService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ProductService.dll"
    environment: {}
    image: "productservice:dev"
    ports: []
    volumes:
    - "/Users/test/Desktop/pet_microservice/ProductService:/app:rw"
    - "/Users/test/Desktop/pet_microservice:/src:rw"
    - "/Users/test/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
